/*   Automatically generated by Iup 3 LED Compiler to C.   */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[      2 ];


void led_load (void)
{
  named[0] = IupSetAtt( "main", IupDialog(
    IupHbox(
      IupLabel( "This is an example of a cross-platform application based on the IUP GUI library." ),
      IupButton( "About...", "" ),
    NULL)
  ), 
    "TITLE", "IUP example", 
    "SIZE", "HALFxHALF", NULL );
}
